// <auto-generated />
namespace HemoSoft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class criacao_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criacao_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201909061922330_criacao_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
